### ISSUE TITLE
Set deployment tests to only run when required

### ISSUE THREAD

**Issue by vvveracruz** [NathOrmond/nt-redaction#2]
ie things like
- changing an .md file
- updating .gitignore
- making changes in jupyter-playground/ should not cause the tests to run

Is this even possible? 🤔

**Comment by nathanorm** [comment]
As a dev you can do commits with `git commit -m "some comment" --no-verify` which will not make the unit tests run.

Test should always be ran prior to a merge with main though to ensure that everything works on the live branch!
